version: '3'

services:
  base:
    build:
      context: .
    image: artifactory.devsh.eu/godbolt/base:latest
    container_name: devsh.godbolt.base
    entrypoint: ["cmd", "/c", "echo", "Created base container is not intended for user usage, exiting!"]
  instance:
    build:
      context: ./project
      args:
      - BUILD_SCRIPT_ARGS=${BUILD_SCRIPT_ARGS}
    environment:
    - BUILD_SCRIPT_ARGS=${BUILD_SCRIPT_ARGS}
    image: artifactory.devsh.eu/godbolt/instance:latest
    container_name: devsh.godbolt.instance
    depends_on:
      - base
    entrypoint: ["build.bat", "%BUILD_SCRIPT_ARGS%"]
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 4G
    ports:
      - "10240:10240"
