version: '3'

include:
   - path:
        - client/dxc/compose.yml
     project_directory: client/dxc
     env_file: env/${THIS_PROJECT_PLATFORM}/.env
   - path:
        - client/llvm/compose.yml
     project_directory: client/llvm
     env_file: env/${THIS_PROJECT_PLATFORM}/.env
   - path:
        - client/shady/compose.yml
     project_directory: client/shady
     env_file: env/${THIS_PROJECT_PLATFORM}/.env
   - path:
        - server/nginx/compose.yml
     project_directory: server/nginx
     env_file: env/${THIS_PROJECT_PLATFORM}/.env
   - path:
        - server/godbolt/compose.yml
     project_directory: server/godbolt
     env_file: env/${THIS_PROJECT_PLATFORM}/.env

services:
  base:
    build:
      context: ./docker
      args:
        THIS_PROJECT_PLATFORM: ${THIS_PROJECT_PLATFORM}
        THIS_PROJECT_ARCH: ${THIS_PROJECT_ARCH}
        THIS_PROJECT_DIRECTORY: ${THIS_PROJECT_DIRECTORY}
        THIS_PROJECT_CLIENT_BIND_DIRECTORY: ${THIS_PROJECT_CLIENT_BIND_DIRECTORY}
        THIS_PROJECT_GIT_REPOSITORIES_DIRECTORY: ${THIS_PROJECT_GIT_REPOSITORIES_DIRECTORY}
        THIS_PROJECT_SYSTEM_PROGRAM_DIRECTORY: ${THIS_PROJECT_SYSTEM_PROGRAM_DIRECTORY}
        THIS_PROJECT_SCRIPTS_DIRECTORY: ${THIS_PROJECT_SCRIPTS_DIRECTORY}
        THIS_PROJECT_TOP_BUILD_DIRECTORY: ${THIS_PROJECT_TOP_BUILD_DIRECTORY}
        THIS_PROJECT_CLIENT_BUILD_DIRECTORY: ${THIS_PROJECT_CLIENT_BUILD_DIRECTORY}
        THIS_PROJECT_CLIENT_INSTALL_DIRECTORY: ${THIS_PROJECT_CLIENT_INSTALL_DIRECTORY}
        THIS_PROJECT_DEPENDENCY_BUILD_DIRECTORY: ${THIS_PROJECT_DEPENDENCY_BUILD_DIRECTORY}
        GIT_INSTALL_DIRECTORY: ${GIT_INSTALL_DIRECTORY}
        PYTHON_INSTALL_DIRECTORY: ${PYTHON_INSTALL_DIRECTORY}
        VS_INSTALL_DIRECTORY: ${VS_INSTALL_DIRECTORY}
        VS_DEV_CMD_DIRECTORY: ${VS_DEV_CMD_DIRECTORY}
        NGINX_INSTALL_DIRECTORY: ${NGINX_INSTALL_DIRECTORY}
        GIT_GODBOLT_REPOSITORY_PATH: ${GIT_GODBOLT_REPOSITORY_PATH}
    image: artifactory.devsh.eu/godbolt/base:latest
    container_name: devsh.godbolt.base
    env_file: 
      - env/${THIS_PROJECT_PLATFORM}/.env
    entrypoint: ["cmd"]
    networks:
      compose_default:

networks:
  compose_default:
    external: true
