version: '3'

services:
  dxc:
    image: artifactory.devsh.eu/godbolt/base:latest
    container_name: devsh.godbolt.client.dxc.${THIS_PROJECT_PLATFORM}.${THIS_PROJECT_ARCH}
    hostname: devsh.godbolt.client.dxc.${THIS_PROJECT_PLATFORM}.${THIS_PROJECT_ARCH}
    profiles: ["client.dxc"]
    env_file: 
      - ../../env/${THIS_PROJECT_PLATFORM}/.env
    networks:
      compose_default:
    depends_on:
      base:
        condition: service_completed_successfully
    entrypoint: ["build.bat", "client.dxc.build"]
    volumes:
      - type: bind
        source: ../../
        target: ${THIS_PROJECT_CLIENT_BIND_DIRECTORY}

networks:
  compose_default:
    external: true